# Generated by Django 3.0.6 on 2020-05-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200524_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='label',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
