# Generated by Django 3.0.6 on 2020-05-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_skills_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='totalGrades',
            field=models.FloatField(blank=True, default=100),
        ),
    ]
